import streamlit as st

def main():
    st.set_page_config(page_title="Python Full-Stack App", layout="centered")

    st.title("Python Full-Stack App (Streamlit Frontend + Backend Logic)")

    st.markdown(
        "This application demonstrates a web frontend built entirely with Python using Streamlit, "
        "along with some simple backend-like logic also written in Python. "
        "All interactive elements and data processing are handled within this single Python script."
    )

    st.subheader("Personalized Greeting (Simple Backend Logic)")
    user_input = st.text_input("Enter your name:", "World")

    # Simple "backend" logic: processing input and generating a message
    if user_input:
        processed_message = f"Hello, {user_input}! This personalized greeting was generated by Python backend logic." 
    else:
        processed_message = "Please enter a name above."

    st.info(processed_message)

    st.subheader("Interactive Counter (State Management)")
    # Initialize session state for persistence
    if 'count' not in st.session_state:
        st.session_state.count = 0

    col1, col2 = st.columns(2)
    with col1:
        if st.button("Increment Counter"): # This triggers a rerun of the script with updated state
            st.session_state.count += 1
    with col2:
        if st.button("Decrement Counter"): # This triggers a rerun of the script with updated state
            st.session_state.count -= 1

    st.metric(label="Current Count", value=st.session_state.count)

    st.subheader("Dynamic Data Display (Backend Data Source)")
    # Simulate fetching data from a "backend"
    data = {
        'Product': ['Apple', 'Banana', 'Cherry', 'Date', 'Elderberry'],
        'Price': [1.20, 0.75, 2.50, 3.00, 4.25],
        'In Stock': [True, True, False, True, False]
    }
    st.dataframe(data, use_container_width=True)

    st.markdown("--- ")
    st.caption("To run this application, ensure Streamlit is installed (`pip install streamlit`), then execute `streamlit run main.py` in your terminal.")

if __name__ == "__main__":
    main()